// <auto-generated />
using FirstProject.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstProject.Dic.FolMig
{
    [DbContext(typeof(FirstContext))]
    [Migration("20240803162539_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FirstProject.DAL.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentDetails")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("varchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FirstProject.DAL.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("DepRef")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosRef")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepRef");

                    b.HasIndex("PosRef");

                    b.ToTable("Department", "EmpDet");
                });

            modelBuilder.Entity("FirstProject.DAL.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("PositionDescription")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PositionTitle")
                        .HasColumnType("varchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("FirstProject.DAL.Employee", b =>
                {
                    b.HasOne("FirstProject.DAL.Department", "deps")
                        .WithMany()
                        .HasForeignKey("DepRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstProject.DAL.Position", "pos")
                        .WithMany()
                        .HasForeignKey("PosRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deps");

                    b.Navigation("pos");
                });
#pragma warning restore 612, 618
        }
    }
}
